add required bits to decode fields tables

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,15 +2,15 @@
 #
 # licence: GPLv3 or later
 # 
-verilator -Wall -I. --top-module saturn_core -cc saturn_core.v hp48_bus.v hp48_io_ram.v hp48_rom.v bus_commands.v
-VERILATOR_STATUS=$?
-if [ "VERILATOR_STATUS" != "0" ]
-then
-    echo "verilator fail"
-    #exit
-fi
+# verilator -Wall -I. --top-module saturn_core -cc saturn-core.v hp48_bus.v hp48_io_ram.v hp48_rom.v bus_commands.v
+# VERILATOR_STATUS=$?
+# if [ "VERILATOR_STATUS" != "0" ]
+# then
+#     echo "verilator fail"
+#     #exit
+# fi
 #iverilog -v -Wall -DSIM -o mask_gen_tb mask_gen.v
-iverilog -v -Wall -DSIM -o rom_tb saturn_core.v
+iverilog -v -Wall -DSIM -o rom_tb saturn-core.v
 IVERILOG_STATUS=$?
 #./mask_gen_tb
 echo "--------------------------------------------------------------------"
